/**
 * Report Service
 * 
 * Generates PDF executive reports using PDFKit.
 * Reports include sections for:
 *   - Executive Summary
 *   - Key Findings
 *   - Top Risks
 *   - Opportunities
 *   - Recommendations
 *   - Forecast Summary
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generate a PDF report
 * 
 * @param {String} reportContent - The text content for the report (from AI)
 * @param {String} projectName - Name of the project
 * @param {Object} datasetInfo - Dataset metadata
 * @param {Array} kpis - Detected KPIs
 * @returns {Promise<String>} Path to the generated PDF file
 */
const generatePDFReport = (reportContent, projectName, datasetInfo, kpis) => {
  return new Promise((resolve, reject) => {
    try {
      // Create reports directory if it doesn't exist
      const reportsDir = path.join(__dirname, '../reports');
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }

      // Generate unique filename
      const fileName = `report_${Date.now()}.pdf`;
      const filePath = path.join(reportsDir, fileName);

      // Create PDF document
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 60, right: 60 },
      });

      // Pipe to file
      const writeStream = fs.createWriteStream(filePath);
      doc.pipe(writeStream);

      // --- Title Page ---
      doc.fontSize(28)
        .font('Helvetica-Bold')
        .text('Executive Report', { align: 'center' })
        .moveDown(0.5);

      doc.fontSize(18)
        .font('Helvetica')
        .fillColor('#4A90D9')
        .text(projectName, { align: 'center' })
        .moveDown(0.3);

      doc.fontSize(12)
        .fillColor('#666666')
        .text(`Generated: ${new Date().toLocaleDateString('en-IN', {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
        })}`, { align: 'center' })
        .moveDown(2);

      // --- Dataset Info ---
      doc.fontSize(10)
        .fillColor('#333333')
        .font('Helvetica-Bold')
        .text('Dataset Information', { underline: true })
        .moveDown(0.3);

      doc.font('Helvetica')
        .fontSize(10);

      if (datasetInfo) {
        doc.text(`File: ${datasetInfo.fileName || 'N/A'}`);
        doc.text(`Rows: ${datasetInfo.rows || 'N/A'}`);
        doc.text(`Columns: ${datasetInfo.columns || 'N/A'}`);
      }

      doc.moveDown(1);

      // --- KPI Summary ---
      if (kpis && kpis.length > 0) {
        doc.fontSize(14)
          .font('Helvetica-Bold')
          .fillColor('#333333')
          .text('Key Performance Indicators')
          .moveDown(0.5);

        doc.fontSize(10).font('Helvetica');

        kpis.forEach((kpi) => {
          const trendIcon = kpi.trend === 'increasing' ? '↑' : kpi.trend === 'decreasing' ? '↓' : '→';
          const trendColor = kpi.trend === 'increasing' ? '#27AE60' : kpi.trend === 'decreasing' ? '#E74C3C' : '#F39C12';

          doc.fillColor('#333333')
            .text(`${kpi.name}: `, { continued: true })
            .fillColor(trendColor)
            .text(`${kpi.value.toLocaleString()} ${trendIcon} ${kpi.percentChange}%`);
        });

        doc.moveDown(1);
      }

      // --- Horizontal Line ---
      doc.moveTo(60, doc.y)
        .lineTo(535, doc.y)
        .stroke('#CCCCCC')
        .moveDown(1);

      // --- Report Content ---
      doc.fillColor('#333333');

      // Parse markdown-like content from AI
      const lines = reportContent.split('\n');

      lines.forEach((line) => {
        const trimmed = line.trim();

        if (trimmed.startsWith('## ')) {
          // Section header
          doc.moveDown(0.5)
            .fontSize(14)
            .font('Helvetica-Bold')
            .fillColor('#2C3E50')
            .text(trimmed.replace('## ', ''))
            .moveDown(0.3);
        } else if (trimmed.startsWith('# ')) {
          // Main header
          doc.moveDown(0.5)
            .fontSize(16)
            .font('Helvetica-Bold')
            .fillColor('#1A1A2E')
            .text(trimmed.replace('# ', ''))
            .moveDown(0.3);
        } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          // Bullet point
          doc.fontSize(10)
            .font('Helvetica')
            .fillColor('#333333')
            .text(`  •  ${trimmed.substring(2)}`, { indent: 10 });
        } else if (trimmed.length > 0) {
          // Regular paragraph
          doc.fontSize(10)
            .font('Helvetica')
            .fillColor('#333333')
            .text(trimmed)
            .moveDown(0.2);
        }
      });

      // --- Footer ---
      doc.moveDown(2)
        .fontSize(8)
        .fillColor('#999999')
        .text('Generated by AI Business Analyst Platform', { align: 'center' })
        .text('This report was auto-generated using AI analysis.', { align: 'center' });

      // Finalize PDF
      doc.end();

      writeStream.on('finish', () => {
        resolve(fileName);
      });

      writeStream.on('error', (err) => {
        reject(err);
      });
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generatePDFReport };
